// automatically generated by the FlatBuffers compiler, do not modify

package snake.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.FlatBufferBuilder;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class AgarFrame extends com.google.flatbuffers.Table {
  public static void ValidateVersion() {}

  public static AgarFrame getRootAsAgarFrame(ByteBuffer _bb) {
    return getRootAsAgarFrame(_bb, new AgarFrame());
  }

  public static AgarFrame getRootAsAgarFrame(ByteBuffer _bb, AgarFrame obj) {
    _bb.order(ByteOrder.LITTLE_ENDIAN);
    return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
  }

  public void __init(int _i, ByteBuffer _bb) {
    __reset(_i, _bb);
  }

  public AgarFrame __assign(int _i, ByteBuffer _bb) {
    __init(_i, _bb);
    return this;
  }

  public snake.fbs.BallState balls(int j) {
    return balls(new snake.fbs.BallState(), j);
  }

  public snake.fbs.BallState balls(snake.fbs.BallState obj, int j) {
    int o = __offset(4);
    return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null;
  }

  public int ballsLength() {
    int o = __offset(4);
    return o != 0 ? __vector_len(o) : 0;
  }

  public snake.fbs.BallState.Vector ballsVector() {
    return ballsVector(new snake.fbs.BallState.Vector());
  }

  public snake.fbs.BallState.Vector ballsVector(snake.fbs.BallState.Vector obj) {
    int o = __offset(4);
    return o != 0 ? obj.__assign(__vector(o), 4, bb) : null;
  }

  public snake.fbs.Vec2 food(int j) {
    return food(new snake.fbs.Vec2(), j);
  }

  public snake.fbs.Vec2 food(snake.fbs.Vec2 obj, int j) {
    int o = __offset(6);
    return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null;
  }

  public int foodLength() {
    int o = __offset(6);
    return o != 0 ? __vector_len(o) : 0;
  }

  public snake.fbs.Vec2.Vector foodVector() {
    return foodVector(new snake.fbs.Vec2.Vector());
  }

  public snake.fbs.Vec2.Vector foodVector(snake.fbs.Vec2.Vector obj) {
    int o = __offset(6);
    return o != 0 ? obj.__assign(__vector(o), 4, bb) : null;
  }

  public static int createAgarFrame(FlatBufferBuilder builder, int ballsOffset, int foodOffset) {
    builder.startTable(2);
    AgarFrame.addFood(builder, foodOffset);
    AgarFrame.addBalls(builder, ballsOffset);
    return AgarFrame.endAgarFrame(builder);
  }

  public static void startAgarFrame(FlatBufferBuilder builder) {
    builder.startTable(2);
  }

  public static void addBalls(FlatBufferBuilder builder, int ballsOffset) {
    builder.addOffset(0, ballsOffset, 0);
  }

  public static int createBallsVector(FlatBufferBuilder builder, int[] data) {
    builder.startVector(4, data.length, 4);
    for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]);
    return builder.endVector();
  }

  public static void startBallsVector(FlatBufferBuilder builder, int numElems) {
    builder.startVector(4, numElems, 4);
  }

  public static void addFood(FlatBufferBuilder builder, int foodOffset) {
    builder.addOffset(1, foodOffset, 0);
  }

  public static int createFoodVector(FlatBufferBuilder builder, int[] data) {
    builder.startVector(4, data.length, 4);
    for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]);
    return builder.endVector();
  }

  public static void startFoodVector(FlatBufferBuilder builder, int numElems) {
    builder.startVector(4, numElems, 4);
  }

  public static int endAgarFrame(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
      __reset(_vector, _element_size, _bb);
      return this;
    }

    public AgarFrame get(int j) {
      return get(new AgarFrame(), j);
    }

    public AgarFrame get(AgarFrame obj, int j) {
      return obj.__assign(__indirect(__element(j), bb), bb);
    }
  }
}
