// automatically generated by the FlatBuffers compiler, do not modify

package snake.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.FlatBufferBuilder;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class BallState extends com.google.flatbuffers.Table {
  public static void ValidateVersion() {}

  public static BallState getRootAsBallState(ByteBuffer _bb) {
    return getRootAsBallState(_bb, new BallState());
  }

  public static BallState getRootAsBallState(ByteBuffer _bb, BallState obj) {
    _bb.order(ByteOrder.LITTLE_ENDIAN);
    return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
  }

  public void __init(int _i, ByteBuffer _bb) {
    __reset(_i, _bb);
  }

  public BallState __assign(int _i, ByteBuffer _bb) {
    __init(_i, _bb);
    return this;
  }

  public String username() {
    int o = __offset(4);
    return o != 0 ? __string(o + bb_pos) : null;
  }

  public ByteBuffer usernameAsByteBuffer() {
    return __vector_as_bytebuffer(4, 1);
  }

  public ByteBuffer usernameInByteBuffer(ByteBuffer _bb) {
    return __vector_in_bytebuffer(_bb, 4, 1);
  }

  public float x() {
    int o = __offset(6);
    return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
  }

  public float y() {
    int o = __offset(8);
    return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
  }

  public float mass() {
    int o = __offset(10);
    return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
  }

  public static int createBallState(
      FlatBufferBuilder builder, int usernameOffset, float x, float y, float mass) {
    builder.startTable(4);
    BallState.addMass(builder, mass);
    BallState.addY(builder, y);
    BallState.addX(builder, x);
    BallState.addUsername(builder, usernameOffset);
    return BallState.endBallState(builder);
  }

  public static void startBallState(FlatBufferBuilder builder) {
    builder.startTable(4);
  }

  public static void addUsername(FlatBufferBuilder builder, int usernameOffset) {
    builder.addOffset(0, usernameOffset, 0);
  }

  public static void addX(FlatBufferBuilder builder, float x) {
    builder.addFloat(1, x, 0.0f);
  }

  public static void addY(FlatBufferBuilder builder, float y) {
    builder.addFloat(2, y, 0.0f);
  }

  public static void addMass(FlatBufferBuilder builder, float mass) {
    builder.addFloat(3, mass, 0.0f);
  }

  public static int endBallState(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
      __reset(_vector, _element_size, _bb);
      return this;
    }

    public BallState get(int j) {
      return get(new BallState(), j);
    }

    public BallState get(BallState obj, int j) {
      return obj.__assign(__indirect(__element(j), bb), bb);
    }
  }
}
