// automatically generated by the FlatBuffers compiler, do not modify

package snake.fbs;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.FlatBufferBuilder;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Vec2 extends com.google.flatbuffers.Table {
  public static void ValidateVersion() {}

  public static Vec2 getRootAsVec2(ByteBuffer _bb) {
    return getRootAsVec2(_bb, new Vec2());
  }

  public static Vec2 getRootAsVec2(ByteBuffer _bb, Vec2 obj) {
    _bb.order(ByteOrder.LITTLE_ENDIAN);
    return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
  }

  public void __init(int _i, ByteBuffer _bb) {
    __reset(_i, _bb);
  }

  public Vec2 __assign(int _i, ByteBuffer _bb) {
    __init(_i, _bb);
    return this;
  }

  public float x() {
    int o = __offset(4);
    return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
  }

  public float y() {
    int o = __offset(6);
    return o != 0 ? bb.getFloat(o + bb_pos) : 0.0f;
  }

  public static int createVec2(FlatBufferBuilder builder, float x, float y) {
    builder.startTable(2);
    Vec2.addY(builder, y);
    Vec2.addX(builder, x);
    return Vec2.endVec2(builder);
  }

  public static void startVec2(FlatBufferBuilder builder) {
    builder.startTable(2);
  }

  public static void addX(FlatBufferBuilder builder, float x) {
    builder.addFloat(0, x, 0.0f);
  }

  public static void addY(FlatBufferBuilder builder, float y) {
    builder.addFloat(1, y, 0.0f);
  }

  public static int endVec2(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
      __reset(_vector, _element_size, _bb);
      return this;
    }

    public Vec2 get(int j) {
      return get(new Vec2(), j);
    }

    public Vec2 get(Vec2 obj, int j) {
      return obj.__assign(__indirect(__element(j), bb), bb);
    }
  }
}
